name: WarpGUI
main: ClickedTran\WarpGUI\WarpGUI
api: 5.0.0
version: 1.1.0
author: ClickedTran
description: it's a plugin that allows you to navigate using the chest menu

permissions:
  warpgui.command.create:
    description: Permission add warp
    default: op
  warpgui.command.remove:
    description: Permission remove warp
    default: op
  warpgui.command.edit:
    description: Permission edit warp
    default: op
  warpgui.command.help:
    description: Permission help all commands warp
    default: op
  warpgui.command:
    description: Permission use command /warpgui
    default: true
